version: "3.9"
services:
  api:
    build: .
    container_name: faucet-api
    volumes:
      - ./config.yml:/app/config.yml
    restart: always

  web:
    build: web
    container_name: faucet-web
    ports:
      - "80:80"
    links:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
    restart: always
